- name: Create a server with ssh key
  hcloud_server: 
    allow_deprecated_image: "{{ item.allow_deprecated_image | default(false) }}"
    api_token: "{{ item.api_token | default(omit) }}"
    backups: "{{ item.backups | default(omit) }}"
    datacenter: "{{ item.datacenter | default(omit) }}"
    delete_protection: "{{ item.delete_protection | default(omit) }}"
    endpoint: "{{ item.endpoint | default(omit) }}"
    firewalls: "{{ item.firewalls | default(omit) }}"
    force: "{{ item.force | default(false) }}"
    force_upgrade: "{{ item.force_upgrade | default(false) }}"
    id: "{{ item.id | default(omit) }}"
    image: "{{ item.image | default(omit) }}"
    labels: "{{ item.labels | default(omit) }}"
    location: "{{ item.location | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    placement_group: "{{ item.placement_group | default(omit) }}"
    rebuild_protection: "{{ item.rebuild_protection | default(omit) }}"
    rescue_mode: "{{ item.rescue_mode | default(omit) }}"
    server_type: "{{ item.server_type | default(omit) }}"
    ssh_keys: "{{ item.ssh_keys | default(omit) }}"
    state: "{{ item.server_state | default(present) }}"
    upgrade_disk: "{{ item.upgrade_disk | default(false) }}"
    user_data: "{{ item.user_data | default(omit) }}"
    volumes: "{{ item.volumes | default(omit) }}"
  loop: "{{ hcloud_servers }}"
  when: hcloud_servers is defined
